ktor:
  development: true
  application:
    development: true
    modules:
      - ir.amirreza.ApplicationKt.module
  deployment:
    port: "$PORT:8080"
    host: 0.0.0.0

db:
  username: "${POSTGRES_USER:amirreza"
  password: "${POSTGRES_PASSWORD:your_password"
  url: "${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres"
  driver: "org.postgresql.Driver"