ktor:
  development: true
  application:
    development: true
    modules:
      - ir.amirreza.ApplicationKt.module
  deployment:
    port: "$PORT:8080"
    host: 0.0.0.0

db:
  username: "${DB_USERNAME:amirreza"
  password: "${DB_PASSWORD:your_password"
  url: "${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres"
  driver: "org.postgresql.Driver"