ktor:
  development: true
  application:
    development: true
    modules:
      - ir.amirreza.ApplicationKt.module
  deployment:
    port: "$PORT:8080"
    host: 0.0.0.0

db:
  username: "$POSTGRES_USER"
  password: "$POSTGRES_PASSWORD"
  url: "$DATABASE_URL"
  driver: "org.postgresql.Driver"